export { default as HomePage } from './home'
export { default as LoginPage } from './login'
export { default as RegistrationPage } from './registration'
export { default as ForgotPasswordPage } from './forgot-password'
export { default as ResetPasswordPage } from './reset-password'
