export const GET_INGREDIENTS_REQUEST: 'GET_INGREDIENTS_REQUEST' =
  'GET_INGREDIENTS_REQUEST'
export const GET_INGREDIENTS_SUCCESS: 'GET_INGREDIENTS_SUCCESS' =
  'GET_INGREDIENTS_SUCCESS'
export const GET_INGREDIENTS_FAILED: 'GET_INGREDIENTS_FAILED' =
  'GET_INGREDIENTS_FAILED'
export const INCREASE_COUNTER: 'INCREASE_COUNTER' = 'INCREASE_COUNTER'
export const DECREASE_COUNTER: 'DECREASE_COUNTER' = 'DECREASE_COUNTER'
export const RESET_COUNTERS: 'RESET_COUNTERS' = 'RESET_COUNTERS'
export const SET_TAB: 'SET_TAB' = 'SET_TAB'
